[package]
name = "cachedirtree"
version = "0.1.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[dependencies]
ego-tree="0.5"
bit-vec = "0.5"
notify = "4.0"
log = "0.4"
derive_builder = "0.7"


[dev-dependencies]
env_logger = "0.5"
